name: Build and Deploy
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Copy index folders
        env:
          SRC_FOLDER_PATH: 'assets'
          TARGET_BRANCH: 'gh-pages'
        run: |
          files=$(find $SRC_FOLDER_PATH -type f) # get the file list
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git fetch                         # fetch branches
          git checkout $TARGET_BRANCH       # checkout to your branch
          git checkout ${GITHUB_REF##*/} -- $files # copy files from the source branch
          git add -A
          git diff-index --quiet HEAD ||  git commit -am "deploy files"  # commit to the repository (ignore if no modification)
          git push origin $TARGET_BRANCH # push to remote branch
      - name: Checkout 🛎️
        uses: actions/checkout@v2.3.1

      - name: Install Canvas Sketch CLI
        run: npm install canvas-sketch-cli@1.11.9 --global
      - name: Install dependencies
        run: npm install
      - name: Build code
        env:
          FILE: sketch-08.js
          FILE_DIR: public/sketch-08
        run: CANVAS_SKETCH_OUTPUT=./outputs canvas-sketch $FILE --dir $FILE_DIR --name index --build --no-compress

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: ./public/
          clean: false
