name: Build and Deploy
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.1
      - name: Move index.html
        run: |
          git pull
          git subtree push --prefix assets origin gh-pages
      - name: Checkout 🛎️
        uses: actions/checkout@v2.3.1

      - name: Install Canvas Sketch CLI
        run: npm install canvas-sketch-cli@1.11.9 --global
      - name: Install dependencies
        run: npm install
      - name: Build code
        env:
          FILE: sketch-08.js
          FILE_DIR: public/sketch-08
        run: CANVAS_SKETCH_OUTPUT=./outputs canvas-sketch $FILE --dir $FILE_DIR --name index --build --no-compress

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: ./public/
          clean: false
